export {
  BROWSER_EVIDENCE_SCHEMA_VERSION,
  BROWSER_MODES,
  DEFAULT_CODEX_BROWSER_SCENARIOS,
  OPTIONAL_TRACE_REAL_BROWSER_MODES,
  REAL_BROWSER_PASS_MODES,
  TRACE_REQUIRED_MODES
} from "./core.js";
