export const COMMAND_NAMES = [
  "validate",
  "codex-start",
  "codex-plugin",
  "codex-ready",
  "codex-task",
  "reviewers",
  "reviewer-report",
  "learn",
  "doctor",
  "status",
  "next",
  "handoff",
  "explain",
  "validation-report",
  "context",
  "sync-state",
  "transition",
  "risk",
  "first-packet",
  "evidence",
  "evidence-manifest",
  "browser-evidence",
  "docs-commands",
  "packet-preflight",
  "brief",
  "agent",
  "orchestrate",
  "migration-preview",
  "migration-apply",
  "cutover-preflight",
  "cutover-report",
  "learning",
  "p2",
  "v23",
  "v24",
  "v25",
  "v26",
  "v27",
  "v28"
];

export function renderUsage({ entrypointPath = ".harness/runtime/state/harness-cli.js" } = {}) {
  return `Usage: node ${entrypointPath} <${COMMAND_NAMES.join("|")}>\n`;
}
